
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.Manager;
import javax.media.Player;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Emmanuel
 */
public class Mapa extends javax.swing.JFrame {
  URL trailer;
    Player reproductor;
    /**
     * Creates new form Mapa
     */
    public Mapa() {
        initComponents();
        setSize(905, 720);
        setResizable(false);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/mapa.jpg")).getImage());
         try {
            //aca nadamas cambien el nombre de la cancion por el estado ejemplo
            //himnosonora.wav , la canciones se pondran en una carpeta aparte en el disco loca c la carpeta se llama MapaAudio
            //trailer = new URL("file:/C:/MapaAudio/mex.wav");
            reproductor = Manager.createRealizedPlayer(trailer);
        } catch (Exception e) {

            // System para que lo vean en codigo
            System.out.println("No se encontro audio");

        }
         
         
          repro.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/play.png")).getImage()));
          repro.setBackground( Color.decode("#005a6b"));
          pausa.setBackground( Color.decode("#005a6b"));
          
        repro.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                reproductor.start();
            }
        });
        pausa.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/pausa.png")).getImage()));

        pausa.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                reproductor.stop();
            }
        });

        // Apaga el hilo del audio              
//        addWindowListener(new java.awt.event.WindowAdapter() {
//            @Override
//            public void windowClosing(java.awt.event.WindowEvent evt) {
//                reproductor.close();
//            }
//        });
         
         
        jPanel2.setDoubleBuffered(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        CHIHUAHUA = new javax.swing.JButton();
        GOLFODEMEXICO = new javax.swing.JButton();
        EUA = new javax.swing.JButton();
        BAJACALIFORNIASUR = new javax.swing.JButton();
        BAJACALIFORNIANORTE = new javax.swing.JButton();
        COAHUILA = new javax.swing.JButton();
        DURANGO = new javax.swing.JButton();
        SONORA = new javax.swing.JButton();
        CHIAPAS = new javax.swing.JButton();
        TABASCO = new javax.swing.JButton();
        OAXACA = new javax.swing.JButton();
        VERACRUZ = new javax.swing.JButton();
        CAMPECHE = new javax.swing.JButton();
        QUINTANAROO = new javax.swing.JButton();
        AGUASCALIENTES = new javax.swing.JButton();
        YUCATAN = new javax.swing.JButton();
        NUEVOLEON = new javax.swing.JButton();
        CENTROAMERICA = new javax.swing.JButton();
        JALISCO = new javax.swing.JButton();
        COLIMA = new javax.swing.JButton();
        ZACATECAS = new javax.swing.JButton();
        NAYARIT = new javax.swing.JButton();
        ESTADOS = new javax.swing.JButton();
        MICHOACAN = new javax.swing.JButton();
        GUERRERO = new javax.swing.JButton();
        SINALOA = new javax.swing.JButton();
        SANLUIS = new javax.swing.JButton();
        TAMAULIPAS = new javax.swing.JButton();
        repro = new javax.swing.JButton();
        pausa = new javax.swing.JButton();
        INFO = new javax.swing.JButton();
        OCEANOPACIFICO = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        CHIHUAHUA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CHIHUAHUA.setText("CHIHUAHUA");
        CHIHUAHUA.setContentAreaFilled(false);
        CHIHUAHUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHIHUAHUAActionPerformed(evt);
            }
        });
        jPanel2.add(CHIHUAHUA);
        CHIHUAHUA.setBounds(240, 120, 120, 130);

        GOLFODEMEXICO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GOLFODEMEXICO.setText("GOLFO DE MÉXICO");
        GOLFODEMEXICO.setContentAreaFilled(false);
        GOLFODEMEXICO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOLFODEMEXICOActionPerformed(evt);
            }
        });
        jPanel2.add(GOLFODEMEXICO);
        GOLFODEMEXICO.setBounds(580, 300, 200, 160);

        EUA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EUA.setText("ESTADOS UNIDOS AMERICANOS");
        EUA.setContentAreaFilled(false);
        EUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EUAActionPerformed(evt);
            }
        });
        jPanel2.add(EUA);
        EUA.setBounds(140, 0, 760, 70);

        BAJACALIFORNIASUR.setFont(new java.awt.Font("Tahoma", 1, 7)); // NOI18N
        BAJACALIFORNIASUR.setText("BAJA CALIFORNIA SUR");
        BAJACALIFORNIASUR.setContentAreaFilled(false);
        BAJACALIFORNIASUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAJACALIFORNIASURActionPerformed(evt);
            }
        });
        jPanel2.add(BAJACALIFORNIASUR);
        BAJACALIFORNIASUR.setBounds(50, 220, 120, 80);

        BAJACALIFORNIANORTE.setFont(new java.awt.Font("Tahoma", 1, 7)); // NOI18N
        BAJACALIFORNIANORTE.setText("BAJA CALIFORNIA NORTE");
        BAJACALIFORNIANORTE.setContentAreaFilled(false);
        BAJACALIFORNIANORTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAJACALIFORNIANORTEActionPerformed(evt);
            }
        });
        jPanel2.add(BAJACALIFORNIANORTE);
        BAJACALIFORNIANORTE.setBounds(0, 130, 140, 60);

        COAHUILA.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        COAHUILA.setText("COAHUILA");
        COAHUILA.setContentAreaFilled(false);
        COAHUILA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COAHUILAActionPerformed(evt);
            }
        });
        jPanel2.add(COAHUILA);
        COAHUILA.setBounds(369, 160, 100, 120);

        DURANGO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DURANGO.setText("DURANGO");
        DURANGO.setContentAreaFilled(false);
        DURANGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DURANGOActionPerformed(evt);
            }
        });
        jPanel2.add(DURANGO);
        DURANGO.setBounds(290, 270, 90, 80);

        SONORA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SONORA.setText("SONORA");
        SONORA.setContentAreaFilled(false);
        SONORA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SONORAActionPerformed(evt);
            }
        });
        jPanel2.add(SONORA);
        SONORA.setBounds(120, 90, 110, 100);

        CHIAPAS.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        CHIAPAS.setText("CHIAPAS");
        CHIAPAS.setContentAreaFilled(false);
        CHIAPAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHIAPASActionPerformed(evt);
            }
        });
        jPanel2.add(CHIAPAS);
        CHIAPAS.setBounds(680, 560, 90, 60);

        TABASCO.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        TABASCO.setText("TABASCO");
        TABASCO.setContentAreaFilled(false);
        TABASCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABASCOActionPerformed(evt);
            }
        });
        jPanel2.add(TABASCO);
        TABASCO.setBounds(670, 520, 70, 20);

        OAXACA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        OAXACA.setText("OAXACA");
        OAXACA.setContentAreaFilled(false);
        OAXACA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OAXACAActionPerformed(evt);
            }
        });
        jPanel2.add(OAXACA);
        OAXACA.setBounds(550, 540, 90, 80);

        VERACRUZ.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        VERACRUZ.setText("VERACRUZ");
        VERACRUZ.setContentAreaFilled(false);
        VERACRUZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VERACRUZActionPerformed(evt);
            }
        });
        jPanel2.add(VERACRUZ);
        VERACRUZ.setBounds(570, 470, 90, 50);

        CAMPECHE.setFont(new java.awt.Font("Tahoma", 1, 7)); // NOI18N
        CAMPECHE.setText("CAMPECHE");
        CAMPECHE.setContentAreaFilled(false);
        CAMPECHE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAMPECHEActionPerformed(evt);
            }
        });
        jPanel2.add(CAMPECHE);
        CAMPECHE.setBounds(740, 490, 80, 50);

        QUINTANAROO.setFont(new java.awt.Font("Tahoma", 1, 6)); // NOI18N
        QUINTANAROO.setText("QUINTA ROO");
        QUINTANAROO.setContentAreaFilled(false);
        QUINTANAROO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QUINTANAROOActionPerformed(evt);
            }
        });
        jPanel2.add(QUINTANAROO);
        QUINTANAROO.setBounds(820, 470, 80, 50);

        AGUASCALIENTES.setFont(new java.awt.Font("Tahoma", 1, 7)); // NOI18N
        AGUASCALIENTES.setText("AGUASCALIENTES");
        AGUASCALIENTES.setContentAreaFilled(false);
        AGUASCALIENTES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGUASCALIENTESActionPerformed(evt);
            }
        });
        jPanel2.add(AGUASCALIENTES);
        AGUASCALIENTES.setBounds(350, 400, 100, 20);

        YUCATAN.setFont(new java.awt.Font("Tahoma", 1, 7)); // NOI18N
        YUCATAN.setText("YUCATÁN");
        YUCATAN.setContentAreaFilled(false);
        YUCATAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YUCATANActionPerformed(evt);
            }
        });
        jPanel2.add(YUCATAN);
        YUCATAN.setBounds(790, 400, 70, 50);

        NUEVOLEON.setFont(new java.awt.Font("Tahoma", 1, 5)); // NOI18N
        NUEVOLEON.setText("NUEVO LEÓN");
        NUEVOLEON.setContentAreaFilled(false);
        NUEVOLEON.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        NUEVOLEON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVOLEONActionPerformed(evt);
            }
        });
        jPanel2.add(NUEVOLEON);
        NUEVOLEON.setBounds(460, 260, 65, 70);

        CENTROAMERICA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CENTROAMERICA.setText("CENTROAMERICA");
        CENTROAMERICA.setContentAreaFilled(false);
        CENTROAMERICA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CENTROAMERICAActionPerformed(evt);
            }
        });
        jPanel2.add(CENTROAMERICA);
        CENTROAMERICA.setBounds(750, 610, 140, 40);

        JALISCO.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        JALISCO.setText("JALISCO");
        JALISCO.setContentAreaFilled(false);
        JALISCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JALISCOActionPerformed(evt);
            }
        });
        jPanel2.add(JALISCO);
        JALISCO.setBounds(320, 460, 77, 20);

        COLIMA.setFont(new java.awt.Font("Tahoma", 1, 7)); // NOI18N
        COLIMA.setForeground(new java.awt.Color(255, 255, 255));
        COLIMA.setText("COLIMA");
        COLIMA.setContentAreaFilled(false);
        COLIMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COLIMAActionPerformed(evt);
            }
        });
        jPanel2.add(COLIMA);
        COLIMA.setBounds(320, 500, 60, 20);

        ZACATECAS.setFont(new java.awt.Font("Tahoma", 1, 7)); // NOI18N
        ZACATECAS.setText("ZACATECAS");
        ZACATECAS.setContentAreaFilled(false);
        ZACATECAS.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ZACATECAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZACATECASActionPerformed(evt);
            }
        });
        jPanel2.add(ZACATECAS);
        ZACATECAS.setBounds(370, 330, 73, 30);

        NAYARIT.setFont(new java.awt.Font("Tahoma", 1, 7)); // NOI18N
        NAYARIT.setForeground(new java.awt.Color(255, 255, 255));
        NAYARIT.setText("NAYARIT");
        NAYARIT.setContentAreaFilled(false);
        NAYARIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAYARITActionPerformed(evt);
            }
        });
        jPanel2.add(NAYARIT);
        NAYARIT.setBounds(300, 410, 70, 20);

        ESTADOS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ESTADOS.setContentAreaFilled(false);
        ESTADOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESTADOSActionPerformed(evt);
            }
        });
        jPanel2.add(ESTADOS);
        ESTADOS.setBounds(460, 450, 110, 80);

        MICHOACAN.setFont(new java.awt.Font("Tahoma", 1, 7)); // NOI18N
        MICHOACAN.setText("MICHOACÁN");
        MICHOACAN.setContentAreaFilled(false);
        MICHOACAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICHOACANActionPerformed(evt);
            }
        });
        jPanel2.add(MICHOACAN);
        MICHOACAN.setBounds(377, 510, 80, 20);

        GUERRERO.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        GUERRERO.setText("GUERRERO");
        GUERRERO.setContentAreaFilled(false);
        GUERRERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUERREROActionPerformed(evt);
            }
        });
        jPanel2.add(GUERRERO);
        GUERRERO.setBounds(440, 540, 90, 50);

        SINALOA.setFont(new java.awt.Font("Tahoma", 1, 7)); // NOI18N
        SINALOA.setForeground(new java.awt.Color(255, 255, 255));
        SINALOA.setText("SINALOA");
        SINALOA.setContentAreaFilled(false);
        SINALOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SINALOAActionPerformed(evt);
            }
        });
        jPanel2.add(SINALOA);
        SINALOA.setBounds(210, 250, 70, 80);

        SANLUIS.setFont(new java.awt.Font("Tahoma", 1, 7)); // NOI18N
        SANLUIS.setText("SAN LUI POTOSI");
        SANLUIS.setContentAreaFilled(false);
        SANLUIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SANLUISActionPerformed(evt);
            }
        });
        jPanel2.add(SANLUIS);
        SANLUIS.setBounds(440, 385, 90, 40);

        TAMAULIPAS.setFont(new java.awt.Font("Tahoma", 1, 7)); // NOI18N
        TAMAULIPAS.setText("TAMAULIPAS");
        TAMAULIPAS.setContentAreaFilled(false);
        TAMAULIPAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAMAULIPASActionPerformed(evt);
            }
        });
        jPanel2.add(TAMAULIPAS);
        TAMAULIPAS.setBounds(480, 330, 80, 60);

        repro.setBackground(Color.decode("#e3c682"));
        repro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/play.png"))); // NOI18N
        repro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproActionPerformed(evt);
            }
        });
        jPanel2.add(repro);
        repro.setBounds(580, 630, 50, 50);

        pausa.setBackground(Color.decode("#e3c682"));
        pausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pausa.png"))); // NOI18N
        pausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausaActionPerformed(evt);
            }
        });
        jPanel2.add(pausa);
        pausa.setBounds(640, 630, 50, 50);

        INFO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        INFO.setContentAreaFilled(false);
        INFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INFOActionPerformed(evt);
            }
        });
        jPanel2.add(INFO);
        INFO.setBounds(40, 520, 160, 130);

        OCEANOPACIFICO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        OCEANOPACIFICO.setText("OCEANO PACIFICO");
        OCEANOPACIFICO.setContentAreaFilled(false);
        OCEANOPACIFICO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OCEANOPACIFICOActionPerformed(evt);
            }
        });
        jPanel2.add(OCEANOPACIFICO);
        OCEANOPACIFICO.setBounds(0, 390, 300, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GIF.gif"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, -20, 920, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EUAActionPerformed


    }//GEN-LAST:event_EUAActionPerformed

    private void CHIHUAHUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHIHUAHUAActionPerformed
        InfoEstado i = new InfoEstado();
        i.setTitle("CHIHUAHUA(CHIHUAHUA)");
        i.setNomEstado("CHIHUAHUA");
        i.setNomcapital("Chihuahua");
        i.setComida("Chile colorado con carne seca, la machaca con huevo, tortillas de harina");
        //i.setMusica("file:/C:/MapaAudio/chihua.wav");
        i.setPersonaje1("Francisco Villa");
        i.setPersonaje2("Luis Terrazas Fuentes");
        i.setPersonaje3("Joaquín Terrazas");
        i.setPersonaje4("Jesús Urueta ");
        i.setRxtension("179,355 km²");
        i.setMunicipios("67");
        i.setHabitantes("1,019,609 de personas");
        i.setLargo(80, 380, 300, 260); //250

        i.setEscudo("/Imagenes/escudochi.png");
        i.setMapa("/Imagenes/mapachia.png");

        String[] regiones = {"Sierra", "Llanura o Meseta",
            "Desierto", "", "",
            "", "",
            "", "", "",
            "", "",
            "", "", "", ""};
        i.setRegiones(regiones);
        String[] tradiciones = {"La feria de Santa Rita.", "Día de San Isidro labrador",
            "Día de la Virgen de los Remedios", "Dia de Santa Barbara"};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicioneschi2.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicioneschi.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicioneschi3.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicioneschi4.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicioneschi5.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicioneschi6.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicioneschi7.png")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicioneschi8.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicioneschi9.jpg")).getImage())

        };
        i.setImagenes(icons);
        i.setVisible(true);

    }//GEN-LAST:event_CHIHUAHUAActionPerformed

    private void SONORAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SONORAActionPerformed
        InfoEstado i = new InfoEstado();
        i.setNomEstado("SONORA");
        i.setTitle("SONORA(HERMOSILLO)");
        i.setNomcapital("Hermosillo");
        i.setComida("Frijoles maneados, Atole de calabaza, Wakabaki,Chimichanga");
        //i.setMusica("file:/C:/MapaAudio/sono.wav");
        i.setPersonaje1("Plutarco Elias Calles");
        i.setPersonaje2("Álvaro Obregón");
        i.setPersonaje3("Felix Maria Zuloaga");
        i.setPersonaje4("Luis Donaldo Colosio");
        i.setRxtension("179,355 km²");
        i.setMunicipios("69");
        i.setHabitantes("3,000,000 de personas");
        i.setLargo(80, 380, 250, 260); //250

        i.setEscudo("/Imagenes/escudosonora.png");
        i.setMapa("/Imagenes/mapasonora.png");

        String[] regiones = {"Sierra Occidental", "Montañas y Valles paralelos",
            "desierto de Sonora", "Costa del Golfo de California", "",
            "", "",
            "", "", "",
            "", "",
            "", "", "", ""};
        i.setRegiones(regiones);
        String[] tradiciones = {"Dia de la Virgen de Guadalupe", "Fiesta del Valle del Yaqui",
            "Festividad de San Francisco de Asís", "Fiesta de San Juan Bautista."};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionessonora5.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionessonora8.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionessonora7.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionessonora6.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionessonora4.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionessonora3.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionessonora2.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionessonora.jpg")).getImage())

        };
        i.setImagenes(icons);
        i.setVisible(true);

    }//GEN-LAST:event_SONORAActionPerformed

    private void COAHUILAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COAHUILAActionPerformed
      
        
        InfoEstado i = new InfoEstado();
        i.setNomEstado("COAHUILA");
        i.setTitle("COAHUILA(SALTILLO)");
        i.setNomcapital("Saltillo");
        i.setComida("Nachos,Discada,Miguitas,Chorizo de Múzquiz");
       // i.setMusica("file:/C:/MapaAudio/coah.wav");
        i.setPersonaje1("Venustiano Carranza");
        i.setPersonaje2("Francisco I. Madero");
        i.setPersonaje3("Emilio Carranza");
        i.setPersonaje4("Eulalio Gutiérrez");
        i.setRxtension("151,595 km²");
        i.setMunicipios("38");
        i.setHabitantes("2,955,000 millones de personas");
        i.setEscudo("/Imagenes/esccoa.png");
        i.setMapa("/Imagenes/mapcoa.png");

        String[] regiones = {"Región Norte", "Región Carbonifera",
            "Región Centro-Desierto", "Región Laguna", "Región Sur",
            "", "",
            "", "", "",
            "", "",
            "", "", "",""};
        i.setRegiones(regiones);
        String[] tradiciones = {"Festival del dulce y la nuez", "Fiestas de San Andrés",
            "Danza de la lechuguilla", "Danzas kikapoo"};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/dulcecoa.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/danzaco.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/fiestaco.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/cc.jpg")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true);        
    }//GEN-LAST:event_COAHUILAActionPerformed

    private void DURANGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DURANGOActionPerformed
       
         InfoEstado i = new InfoEstado();
        i.setNomEstado("Durango");
        i.setTitle("DURANGO(DURANGO)");
        i.setNomcapital("Durango");
        i.setComida("Caldillo durangueño, Asado de boda, Tamales,"
                + "Bocaditos de Nuez");
        ///himnogue.wav
        //i.setMusica("file:/C:/MapaAudio/dura.wav");
        i.setPersonaje1("Ricardo Castro Herrera");
        i.setPersonaje2("Benigno Montoya Muñoz");
        i.setPersonaje3("José Doroteo Arango Arámbula");
        i.setPersonaje4("Guadalupe Victoria");
        i.setRxtension("125,381 km²");
        i.setMunicipios("39");
        i.setHabitantes("1.755 millones de personas");
        i.setEscudo("/Imagenes/durango.png");
        i.setMapa("/Imagenes/mapadurango.png");

        String[] regiones = {"Semidesierto", "Los Valles",
            "La Sierra", "Región De Las Quebradas", "",
            "", "",
            "", "", "",
            "", "",
            "", "", "",""};
        i.setRegiones(regiones);
        String[] tradiciones = {"Feria de la uva", "Día de San José ",
            "Feria de la manzana", ""};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/durango1.png")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/durango2.png")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/durango3.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/durango4.png")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true);
    
    }//GEN-LAST:event_DURANGOActionPerformed

    private void OAXACAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OAXACAActionPerformed

        InfoEstado i = new InfoEstado();
        i.setNomEstado("OAXACA");
        i.setTitle("OAXACA(OAXACA DE JUÁREZ)");
        i.setNomcapital("Oaxaca de Juárez");
        i.setComida("7 moles,chapulines,tlayudas,mezcal,pan de yema");
        //i.setMusica("file:/C:/MapaAudio/himnooax.wav");
        i.setPersonaje1("Benito Juárez");
        i.setPersonaje2("Porfirio Diaz");
        i.setPersonaje3("José Vasconcelos");
        i.setPersonaje4("Ricardo Flores Magón");
        i.setRxtension("95,364 km²");
        i.setMunicipios("570");
        i.setHabitantes("3,967,889 millones de personas");
        i.setEscudo("/Imagenes/escudo-oaxaca.png");
        i.setMapa("/Imagenes/OaxacaEstadoMapa.png");

        String[] regiones = {"Costa", "Istmo",
            "Valles Centrales", "Sierra norte", "Sierra sur",
            "Mixteca", "Cañada",
            "Papaloapan", "", "",
            "", "",
            "", "", "", ""};
        i.setRegiones(regiones);
        String[] tradiciones = {"Guelaguetza", "Muerteadas",
            "Velas istmeñas", ""};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/1.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/2.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/3.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/4.jpg")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true);

    }//GEN-LAST:event_OAXACAActionPerformed

    private void CHIAPASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHIAPASActionPerformed

        InfoEstado i = new InfoEstado();
        i.setNomEstado("CHIAPAS");
        i.setTitle("CHIAPAS(TUXTLA GUTIÉRREZ)");
        i.setNomcapital("Tuxtla Gutiérrez");
        i.setComida("Cochito horneado,Tascalate,Sopa de pan");
        ///yucatan.wav
        //i.setMusica("file:/C:/MapaAudio/chiapas.wav");
        i.setPersonaje1("Fray Matías Antonio de Córdoba y Ordóñez");
        i.setPersonaje2("Joaquín Miguel Gutiérrez");
        i.setPersonaje3("José Emilio Grajales Moguel");
        i.setPersonaje4("Carlos Cáceres López ");
        i.setRxtension("73,311 km²");
        i.setMunicipios("124");
        i.setHabitantes("5,218,000 millones de personas");
        i.setEscudo("/Imagenes/chiapasescudo.png");
        i.setMapa("/Imagenes/mapachia.png");

        String[] regiones = {"Metropolitana", "Valles Zoque",
            "Mezcalapa", "De los Llanos", "Altos Tsotsil-Tseltal",
            "La Frailesca", "De Los Bosques",
            "Norte", "Istmo-Costa", "Soconusco",
            "Sierra Mariscal", "Selva Lacandona",
            "Maya", "Tulijá Tzeltal Chol", "Meseta Comiteca Tojolabal",""};
        i.setRegiones(regiones);

        String[] tradiciones = {"Fiesta de San Cristóbal", "Fiesta de los Parachicos",
            "Desfile de los Santos", "Día de la Candelaria"};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/cochito.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/parac.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/zocalo.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/cascada.jpg")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true);


    }//GEN-LAST:event_CHIAPASActionPerformed

    private void INFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INFOActionPerformed

        new InfoDesarrolladores().setVisible(true);
    }//GEN-LAST:event_INFOActionPerformed

    private void YUCATANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YUCATANActionPerformed
        InfoEstado i = new InfoEstado();
        i.setNomEstado("YUCATÁN");
        i.setNomcapital("Mérida");
        i.setTitle("YUCATÁN(MÉRIDA)");
        i.setComida("Cochinita pibil,Panuchos,Sopa de lima,"
                + "Papadzules");
        ///himnoyuc.wav
        //i.setMusica("file:/C:/MapaAudio/yuca.wav");
        i.setPersonaje1("Andrés Quintana Roo");
        i.setPersonaje2("Francisco Cantón Rosado");
        i.setPersonaje3("Manuel Cepeda Peraza");
        i.setPersonaje4("José Peón Contreras");
        i.setRxtension("43,379 km²");
        i.setMunicipios("106");
        i.setHabitantes("2,097,000 millones de personas");
        i.setEscudo("/Imagenes/yucatanescudo.png");
        i.setMapa("/Imagenes/mapayuc.png");

        String[] regiones = {"Abalá", "Acancéh",
            "Akil", "Baca", "Bokobá",
            "Buctzotz", "Cacalchén",
            "Calotmul.", "", "",
            "", "",
            "", "", "",""};
        i.setRegiones(regiones);
        String[] tradiciones = {"Mamá Linda", "Vaquería",
            "El festival de Equinoccio", ""};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/papadzul.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/ecc.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/trajestu.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/playarosa.jpg")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true);
    }//GEN-LAST:event_YUCATANActionPerformed

    private void GUERREROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUERREROActionPerformed
        InfoEstado i = new InfoEstado();
        i.setNomEstado("GUERRERO");
        i.setTitle("GUERRERO(CHILPANCINGO)");
        i.setNomcapital("Chilpancingo");
        i.setComida("Pozole Guerrerense,Pulpo Enamorado,Jumiles,"
                + "Pescado a la talla");
        ///himnogue.wav
        //i.setMusica("file:/C:/MapaAudio/querre.wav");
        i.setPersonaje1("Vicente Guerrero");
        i.setPersonaje2("Nicolás Bravo");
        i.setPersonaje3("Juan Álvarez");
        i.setPersonaje4("Ignacio Manuel Altamirano");
        i.setRxtension("64,281 km²");
        i.setMunicipios("500");
        i.setHabitantes("3,533,000 millones de personas");
        i.setEscudo("/Imagenes/guerreroescudo.png");
        i.setMapa("/Imagenes/regionesguerrero.png");

        String[] regiones = {"Acapulco", "Costa Chica",
            "Costa Grande", "Centro", "La Montaña",
            "Norte", "Tierra Caliente",
            "Sierra", "", "",
            "", "",
            "", "", "", ""};
        i.setRegiones(regiones);
        String[] tradiciones = {"Fiesta de San Isidro", "Festividad patronal de San Sebastián y Santa Prisca ",
            "", ""};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/guerrerocultura1.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/pulpo.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Ixtapa.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tapete.jpg")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true);

    }//GEN-LAST:event_GUERREROActionPerformed

    private void ZACATECASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZACATECASActionPerformed

         InfoEstado i = new InfoEstado();
        i.setNomEstado("ZACATECAS");
        i.setNomcapital("Zacatecas");
        i.setTitle("ZACATECAS(ZACATECAS)");
        i.setComida("Asado de boda,Cola de res zacatecana,Enchiladas zacatecanas");
        //i.setMusica("file:/C:/MapaAudio/zac.wav");
        i.setPersonaje1("Francisco Aguilar y Urízar");
        i.setPersonaje2("Genaro Codina Fernández");
        i.setPersonaje3("Úrsulo García Arizmendi");
        i.setPersonaje4("Fernando Villalpando Ávila");
        i.setRxtension("77,684 km²");
        i.setMunicipios("58");
        i.setHabitantes("1,579,000 millones de personas");
        i.setEscudo("/Imagenes/esczac.png");
        i.setMapa("/Imagenes/mapazac.png");

        String[] regiones = {"Sierra Madre Oriental", "La Masa del Centro",
            "La Sierra Madre Occidental", "El Eje Neovolcánico", "",
            "", "",
            "", "", "",
            "", "",
            "", "", "",""};
        i.setRegiones(regiones);
        String[] tradiciones = {"Mañanitas de Abril", "Morismas de Bracho",
            "Feria Nacional del Zacatecas", "Toma de Zacatecas"};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/feriazac.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/mor.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/platozac.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/trajezac.jpg")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true);
       
    }//GEN-LAST:event_ZACATECASActionPerformed

    private void NUEVOLEONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVOLEONActionPerformed
       
         InfoEstado i = new InfoEstado();
        i.setNomEstado("NUEVO LEÓN");
        i.setTitle("NUEVO LEÓN(MONTERREY)");
        i.setNomcapital("Monterrey");
        i.setComida("Carne asada, Capirotada,"
                + "Atropellado");
        ///himnoyuc.wav
        //i.setMusica("file:/C:/MapaAudio/nl.wav");
        i.setPersonaje1("JDavid Toscana");
        i.setPersonaje2("Ricardo Elizondo Elizondo");
        i.setPersonaje3("Agustín Basave Fernández del Valle");
        i.setPersonaje4("Manuel María de Llano");
        i.setRxtension("64,156 km²");
        i.setMunicipios("51");
        i.setHabitantes("1,136 millones de personas");
        i.setEscudo("/Imagenes/nuevoleon.png");
        i.setMapa("/Imagenes/mapanuevoleon.png");

        String[] regiones = {"Metropolitana", "Noroeste",
            "Noreste", "Sur", "Valle Del Pilón",
            "Centro Periférica", "",
            "", "", "",
            "", "",
            "", "", "",""};
        i.setRegiones(regiones);
        String[] tradiciones = {"Feria del Machacado", "Feria de la Manzana",
            "Feria de la Nuez", "Feria de Villaseca"};
        i.setTradiciones(tradiciones);

        ImageIcon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/monterrey1.png")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/monterrey2.png")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/monterrey3.png")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/monterrey4.png")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true);
       
    }//GEN-LAST:event_NUEVOLEONActionPerformed

    private void JALISCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JALISCOActionPerformed
       
         InfoEstado i = new InfoEstado();
        i.setNomEstado("JALISCO");
        i.setTitle("JALISCO(GUADALAJARA)"); 
        i.setNomcapital("Guadalajara");
        i.setComida("Tortas Ahogadas,Jericallas,Menudo,Birria");
        //i.setMusica("file:/C:/MapaAudio/jal.wav");
        i.setPersonaje1("Juan Rulfo");
        i.setPersonaje2("Juan José Arreola");
        i.setPersonaje3("José Clemente Orozco");
        i.setPersonaje4("Consuelo Velázquez");
        i.setRxtension("78,588 km²");
        i.setMunicipios("125");
        i.setHabitantes("2,718,000 millones de personas");
        i.setEscudo("/Imagenes/escudojal.png");
        i.setMapa("/Imagenes/mapajali.png");

        String[] regiones = {"Costa Norte", "Costa Sur",
            "Sierra Occidental", "Sierra de Amula", "Sur",
            "Sureste", "Valles",
            "Centro", "Norte", "Ciénega",
            "Altos sur", "Altos norte",
            "", "", "",""};
        i.setRegiones(regiones);
        String[] tradiciones = {"Fiesta de Santo Santiago", "Fundación de Guadalajara",
            "Festival Cultural de Mayo", "Encuentro Internacional del Mariachi"};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/torta.png")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/trajeja.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/juguete.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/cj.jpg")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true);
        
    }//GEN-LAST:event_JALISCOActionPerformed

    private void MICHOACANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICHOACANActionPerformed
        // TODO add your handling code here:
        InfoEstado i = new InfoEstado();
        i.setNomEstado("MICHOACÁN");
        i.setTitle("MICHOACÁN(MORELIA)");
        i.setNomcapital("Morelia");
        i.setComida("Corundas,Charales,Morisqueta,"
                + "Carnitas");
        ///himnoyuc.wav
        //i.setMusica("file:/C:/MapaAudio/micho.wav");
        i.setPersonaje1("José María Morelos y Pavón");
        i.setPersonaje2("Ignacio López Rayón");
        i.setPersonaje3("Mariano Matamoros");
        i.setPersonaje4("Agustín de Iturbide");
        i.setRxtension("58,599 km²");
        i.setMunicipios("113");
        i.setHabitantes("4,584,000 millones de personas");
        i.setEscudo("/Imagenes/escudomich.png");
        i.setMapa("/Imagenes/micho.png");

        String[] regiones = {"Centro (Morelia)", "Lacustre (Pátzcuaro)",
            "Meseta Purépecha (Uruapan)", "Oriente (Zitácuaro)", "Occidente (Zamora)",
            " Costa(Lázaro Cárdenas)", "",
            "", "", "",
            "", "","",
            "", "", ""};
        i.setRegiones(regiones);
        String[] tradiciones = {"Epifanía", "Día de la candelaria",
            "Martes de carnaval", "Dia de muertos"};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/diamuertos.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/comidamicho.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/michorop.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/zocalomich.jpg")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true);
    }//GEN-LAST:event_MICHOACANActionPerformed

    private void TAMAULIPASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAMAULIPASActionPerformed

 InfoEstado i = new InfoEstado();
        i.setNomEstado("TAMAULIPAS");
        i.setTitle("TAMAULIPAS(CIUDAD VICTORIA)");
        i.setNomcapital("Ciudad Victoria");
        i.setComida("Carne a la tampiqueña,Cabrito enchilado,Jaibas rellenas,Bocoles de el Mante");
        //i.setMusica("file:/C:/MapaAudio/tama.wav");
        i.setPersonaje1("Emilio Portes Gil");
        i.setPersonaje2("Gral. Pedro José Mendez");
        i.setPersonaje3("Gral. Alberto Carrera Torres");
        i.setPersonaje4("Fidencio Trejo Flores");
        i.setRxtension("75,384 km²");
        i.setMunicipios("43");
        i.setHabitantes("3,442,000 millones de personas");
        i.setEscudo("/Imagenes/esctam.png");
        i.setMapa("/Imagenes/mapatam.png");

        String[] regiones = {"Región Fronteriza", "Región Valle de San Fernando",
            "Región Centro", "Región Mante", "Región Sur",
            "Región Altiplano", "",
            "", "", "",
            "", "",
            "", "", "",""};
        i.setRegiones(regiones);
        String[] tradiciones = {"Celebración del Xantolo", "Expo Feria de Tamaulipas ",
            "Feria y Exposición Agrícola y Ganadera", "Carnaval del Puerto de Tampico"};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/xan.png")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/cartam.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tampi.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/trajetam.jpg")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true);
        
       
    }//GEN-LAST:event_TAMAULIPASActionPerformed

    private void SANLUISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SANLUISActionPerformed
        
        InfoEstado i = new InfoEstado();
        i.setNomEstado("SAN LUIS POTOSI");
        i.setTitle("SAN LUIS POTOSI(SAN LUIS POTOSI)");
        i.setNomcapital("San Luis Potosi");
        i.setComida("Enchiladas potosinas,Zacahuil,Tamborcitos,Colonche,Guiso borracho");
        //i.setMusica("file:/C:/MapaAudio/sl.wav");
        i.setPersonaje1("Francisco González Bocanegra");
        i.setPersonaje2("Manuel José Othón");
        i.setPersonaje3("Francisca de la Gándara");
        i.setPersonaje4("José Mariano Jiménez");
        i.setRxtension("61,137 km²");
        i.setMunicipios("58");
        i.setHabitantes("2,718,000 millones de personas");
        i.setEscudo("/Imagenes/escsn.png");
        i.setMapa("/Imagenes/mapasn.png");

        String[] regiones = {"Altiplano", "Centro",
            "Media", "Huasteca", "",
            "", "",
            "", "", "",
            "", "",
            "", "", "",""};
        i.setRegiones(regiones);
        String[] tradiciones = {"Feria Nacional Potosina(FENAPO)", "Xantolo",
            "Los Diablos", "Procesión del Silencio"};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/fena.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/xan.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/enchi.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/sntraje.jpg")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true);
       
        
    }//GEN-LAST:event_SANLUISActionPerformed

    private void CAMPECHEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAMPECHEActionPerformed
        InfoEstado i = new InfoEstado();
        i.setNomEstado("CAMPECHE");
        i.setTitle("CAMPECHE(CAMPECHE)");
        i.setNomcapital("Campeche");
        i.setComida("Pan de cazón,Camarones al coco,Poc chuc,"
                + "Chocolomo");
        ///himnoyuc.wav
        //i.setMusica("file:/C:/MapaAudio/cam.wav");
        i.setPersonaje1("Maria Lavalle Urbina");
        i.setPersonaje2("Román Piña Chan");
        i.setPersonaje3("Pablo García y Montilla");
        i.setPersonaje4("Justo Sierra");
        i.setRxtension("57,924 km²");
        i.setMunicipios("11");
        i.setHabitantes("899,931 mil personas");
        i.setEscudo("/Imagenes/escudocam.png");
        i.setMapa("/Imagenes/mapacam.png");

        String[] regiones = {"Calkiní", "Campeche",
            "Carmen", "Champotón", "Hecelchakán",
            "Hopelchén", "Palizada",
            "Tenabo", "Escárcega", "Calakmul",
            "Candelaria", "",
            "", "", "",""};
        i.setRegiones(regiones);
        String[] tradiciones = {"Feria de San Román", "La Virgen del Carmen",
            "Festival del Centro Histórico de Campeche", "Feria de San Francisco"};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/pancazon.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/playacamp.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/bailecam.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/campeche.jpg")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true);


    }//GEN-LAST:event_CAMPECHEActionPerformed

    private void QUINTANAROOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QUINTANAROOActionPerformed
        InfoEstado i = new InfoEstado();
        i.setNomEstado("QUINTANA ROO");
        i.setTitle("QUINTANA ROO(CHETUMAL)");
        i.setNomcapital("Chetumal(proximamente se cambiara a Cancún)");
        i.setComida("Pescado a la tikin-xic,Pipián,Ceviche de caracol,"
                + "Kibis a la chetumaleña");
        ///yucatan.wav
        //i.setMusica("file:/C:/MapaAudio/qr.wav");
        i.setPersonaje1("Gonzalo Guerrero");
        i.setPersonaje2("Cecilo Chi");
        i.setPersonaje3("Jacinto Pat");
        i.setPersonaje4("Javier Rojo Gómez");
        i.setRxtension("34,205 km²");
        i.setMunicipios("11");
        i.setHabitantes("1,502,000 de personas");
        i.setEscudo("/Imagenes/escudoquin.png");
        i.setMapa("/Imagenes/mapaquin.png");

        String[] regiones = {"Othón P. Blanco", "Bacalar",
            "Benito Juárez", "Cozumel", "Felipe Carrillo Puerto",
            "Isla Mujeres", "José María Morelos",
            "Lázaro Cárdenas", "Puerto Morelos", "Solidaridad",
            "Tulum", "",
            "", "", "",""};
        i.setRegiones(regiones);
        String[] tradiciones = {"El carnaval de Cozumel", "Hanal Pixán",
            "Feria del Cedral", "Fiesta de la Santa Cruz"};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/pescadochetu.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/feriaqr.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/carnaval.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Cancun.jpg")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true);    }//GEN-LAST:event_QUINTANAROOActionPerformed

    private void TABASCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABASCOActionPerformed
           InfoEstado i = new InfoEstado();
        i.setNomEstado("TABASCO");
        i.setNomcapital("Villahermosa");
        i.setComida("Bosto,Albóndigas de Chaya,Pochitoques,Pejelagarto Asado");
        ///yucatan.wav
        //i.setMusica("file:/C:/MapaAudio/tab.wav");
        i.setPersonaje1("José Narciso Rovirosa Andrade");
        i.setPersonaje2("Manuel Sánchez Mármol");
        i.setPersonaje3("Simón Sarlat Nova");
        i.setPersonaje4("José María Pino Suárez");
        i.setRxtension("25,267 km²");
        i.setMunicipios("17");
        i.setHabitantes("2,395,272 millones de personas");
        i.setEscudo("/Imagenes/tabascoesc.png");
        i.setMapa("/Imagenes/mapatab.jpg");

        String[] regiones = {"Subregión Centro", "Subregión Chontalpa",
            "Subregión Sierra", "Subregión Pantanos", "Subregión Los Ríos",
            "", "",
            "", "", "",
            "", "",
            "", "", "",""};
        i.setRegiones(regiones);
        
        String[] tradiciones = {"Carnaval de Tenosique", "El Festival del Chocolate",
            "La Feria de Tabasco", "Ritual de la pesca de la sardina ciega"};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/peje.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/teno.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/trajetab.png")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/cabeza.jpg")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true); 
        
        
    }//GEN-LAST:event_TABASCOActionPerformed

    private void GOLFODEMEXICOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GOLFODEMEXICOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GOLFODEMEXICOActionPerformed

    private void OCEANOPACIFICOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OCEANOPACIFICOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OCEANOPACIFICOActionPerformed

    private void BAJACALIFORNIANORTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAJACALIFORNIANORTEActionPerformed

       
        InfoEstado i = new InfoEstado();
        i.setNomEstado("BAJA CALIFORNIA NORTE");
        i.setTitle("BAJA CALIFORNIA NORTE(MEXICALI)");
        i.setNomcapital("Mexicali");
        i.setComida("Ensalada César,Tacos de pescado,Langosta al Estilo Pueblo Nuevo");
        ///yucatan.wav
        i.setMusica("file:/C:/MapaAudio/bcn.wav");
        i.setPersonaje1("DON HESIQUIO TREVIÑO");
        i.setPersonaje2("Francisco de Ulloa");
        i.setPersonaje3("Juan Rodríguez Cabrillo");
        i.setPersonaje4("Antonio Meléndrez ");
        i.setRxtension("71,450 km²");
        i.setMunicipios("5");
        i.setHabitantes("3,316,000 millones de personas");
        i.setEscudo("/Imagenes/escbcn.png");
        i.setMapa("/Imagenes/mapabcn.png");

        String[] regiones = {"Ensenada", "Mexicali",
            "Tijuana", "Rosarito", "Tecate",
            "", "",
            "", "", "",
            "", "",
            "", "", "",""};
        i.setRegiones(regiones);
        
        String[] tradiciones = {"Fiesta del Sol", "Feria del algodón",
            "Carnaval de San Felpe", "Feria Regional “TECATE EN MARCHA”"};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/bcbaile.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/feriabc.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/playabcn.jpeg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tecate.jpg")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true); 

    }//GEN-LAST:event_BAJACALIFORNIANORTEActionPerformed

    private void BAJACALIFORNIASURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAJACALIFORNIASURActionPerformed

InfoEstado i = new InfoEstado();
        i.setNomEstado("BAJA CALIFORNIA SUR");
        i.setTitle("BAJA CALIFORNIA SUR(LA PAZ)");
        i.setNomcapital("La Paz");
        i.setComida("Filete imperial de camarón,Machaca de mantarraya,Langosta en mantequilla");
        ///yucatan.wav
        //i.setMusica("file:/C:/MapaAudio/bcs.wav");
        i.setPersonaje1("Manuel Márquez de León");
        i.setPersonaje2("Rosaura Zapata Cano");
        i.setPersonaje3("Jesús Castro Agúndez");
        i.setPersonaje4("Domingo Caballo Félix");
        i.setRxtension("75,675 km²");
        i.setMunicipios("5");
        i.setHabitantes("763,929 miles de personas");
        i.setEscudo("/Imagenes/bcsesc.png");
        i.setMapa("/Imagenes/mapabcs.png");

        String[] regiones = {"Comondú", "Mulegé",
            "La Paz", "Los Cabos", "Loreto",
            "", "",
            "", "", "",
            "", "",
            "", "", "",""};
        i.setRegiones(regiones);
        
        String[] tradiciones = {"Festival de pitahayas", "Carnaval de San Felipe",
            "Días de los Santos Patronos","Fiesta de San Francisco Javier"};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/bcsc.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/manta.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/pita.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/trajebcs.png")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true);
    }//GEN-LAST:event_BAJACALIFORNIASURActionPerformed

    private void VERACRUZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VERACRUZActionPerformed
        InfoEstado i = new InfoEstado();
        i.setNomEstado("VERACRUZ");
        i.setTitle("VERACRUZ(XALAPA)");
        i.setNomcapital("Xalapa");
        i.setComida("Pescado a la Veracruzana,Camarones al coco,Vuelve a la vida");
        ///yucatan.wav
        //i.setMusica("file:/C:/MapaAudio/vera.wav");
        i.setPersonaje1("Salvador Díaz Mirón");
        i.setPersonaje2("Adolfo Ruiz Cortines");
        i.setPersonaje3("Agustín Lara");
        i.setPersonaje4("Francisco Gabilondo Soler");
        i.setRxtension("71,820 km²");
        i.setMunicipios("212");
        i.setHabitantes("8,113,000 millones de personas");
        i.setEscudo("/Imagenes/escudover.png");
        i.setMapa("/Imagenes/veramapa.png");

        String[] regiones = {"Huasteca", "Sierra de Huayacocotla",
            "Totonacapan", "Grandes Montañas", "Llanuras de Sotavento",
            "Los Tuxtlas", "Istmo de Tehuantepec",
            "", "", "",
            "", "",
            "", "", "", ""};
        i.setRegiones(regiones);

        String[] tradiciones = {"Carnaval de Veracruz", "Feria del café",
            "Fiestas de Naolinco", "Fiestas de la Primavera"};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/carnavalver.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/pescadover.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/trajever.jpg")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/puerto.jpg")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true);


    }//GEN-LAST:event_VERACRUZActionPerformed

    private void SINALOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SINALOAActionPerformed
        
        InfoEstado i = new InfoEstado();
        i.setNomEstado("SINALOA");
        i.setTitle("SINALOA(CULIACÁN)");
        i.setNomcapital("‎Culiacán");
        i.setComida("Camarones a la diabla, Capirotada, Chilorio");
        ///yucatan.wav
        //i.setMusica("file:/C:/MapaAudio/sin.wav");
        i.setPersonaje1("Agustina Ramírez");
        i.setPersonaje2("Antonio Rosales");
        i.setPersonaje3("Plácido Vega");
        i.setPersonaje4("Ramón F. Iturbe");
        i.setRxtension("58,200 km²");
        i.setMunicipios("18");
        i.setHabitantes("3.216 millones de personas");
        i.setEscudo("/Imagenes/sinaloa.png");
        i.setMapa("/Imagenes/mapasinaloa.png");

        String[] regiones = {"Zona Norte","Zona Centro Norte",
            "Zona Centro","Zona Sur","",
            "", "",
            "", "", "",
            "", "",
            "", "", "",""};
        i.setRegiones(regiones);

        String[] tradiciones = {"Carnaval de Mazatlán", "Fiesta de la Primavera",
            "Sombreros de El Fuerte", "Ulama"};
        i.setTradiciones(tradiciones);

        Icon icons[] = {
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/sinaloa1.png")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/sinaloa2.png")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/sinaloa3.png")).getImage()),
            new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/sinaloa4.png")).getImage())
        };
        i.setImagenes(icons);
        i.setVisible(true);
    }//GEN-LAST:event_SINALOAActionPerformed

    private void ESTADOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESTADOSActionPerformed
             new prueba().setVisible(true);


    }//GEN-LAST:event_ESTADOSActionPerformed

    private void NAYARITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAYARITActionPerformed
       
         InfoEstado i = new InfoEstado();
            i.setNomEstado("NAYARIT");
            i.setTitle("NAYARIT(TEPIC)");
            i.setNomcapital("Tepic");
            i.setComida("Aguachile, Ceviche de Pescado, Chicharrón de Pescado,Tamales de Camarón.");
            ///yucatan.wav
            //i.setMusica("file:/C:/MapaAudio/naya.wav");
            i.setPersonaje1("Francisco Severo Maldonado");
            i.setPersonaje2("Juan Escutia");
            i.setPersonaje3("Amado Nervo");
            i.setPersonaje4("José Francisco Arroyo");
            i.setRxtension("27 857 km²");
            i.setMunicipios("20");
            i.setHabitantes("1,181 millones de personas");
            i.setLargo(80, 350, 350, 290);//320
            i.setEscudo("/Imagenes/escudonayarit.png");
            i.setMapa("/Imagenes/mapanayarit.png");

            String[] regiones = {"Region Norte", "Region Sierra",
                "Region Centro", "Region Costa Norte", "Region Costa Sur",
                "", "",
                "", "", "",
                "", "",
                "", "", "", ""};
            i.setRegiones(regiones);

            String[] tradiciones = {"Feria Nayarit", "Feria Nacional de la Primavera",
                "Cambio de Varas", "Feria del Elote"};
            i.setTradiciones(tradiciones);

            Icon icons[] = {
                new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionesnayarit.jpg")).getImage()),
                new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionesnayarit2.jpg")).getImage()),
                new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionesnayarit3.jpg")).getImage()),
                new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionesnayarit4.jpg")).getImage()),
                new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionesnayarit5.jpg")).getImage()),
                new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionesnayarit6.jpg")).getImage()),
                new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionesnayarit7.jpeg")).getImage())
            };
            i.setImagenes(icons);
            i.setVisible(true);
        
        
    }//GEN-LAST:event_NAYARITActionPerformed

    private void COLIMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COLIMAActionPerformed
     
        
         InfoEstado i = new InfoEstado();
            i.setNomEstado("COLIMA");
            i.setTitle("COLIMA(COLIMA)");
            i.setNomcapital("Colima");
            i.setComida("Sopitos Tortillas, Pozole de cerdo, Tejuino Bebida de maíz fermentado.");
            ///yucatan.wav
            //i.setMusica("file:/C:/MapaAudio/col.wav");
            i.setPersonaje1("Alejandro Rangel Hidalgo (Pintor)");
            i.setPersonaje2("Alfonso Michel (Pintor)");
            i.setPersonaje3("Anastacio Brizuela (Militar)");
            i.setPersonaje4("Balbino Dávalos (Poeta)");
            i.setRxtension("5,625 km²");
            i.setMunicipios("10");
            i.setHabitantes("711,235 mil personas");
            i.setLargo(50, 350, 380, 300);//320
            i.setEscudo("/Imagenes/escudocolima.png");
            i.setMapa("/Imagenes/mapacolima.png");

            String[] regiones = {"Región Norte", "Region Sur",
                "", "", "",
                "", "",
                "", "", "",
                "", "",
                "", "", "", ""};
            i.setRegiones(regiones);

            String[] tradiciones = {"Fiesta de la Virgen de la Salud", "Fiesta taurina",
                " Feria agrícola, ganadera, comercial e industrial", "Fiesta de la Virgen de Guadalupe"};
            i.setTradiciones(tradiciones);

            Icon icons[] = {
                new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionescolima.jpg")).getImage()),
                new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionescolima2.jpg")).getImage()),
                new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionescolima3.jpg")).getImage()),
                new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionescolima4.jpg")).getImage()),
                new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionescolima5.jpg")).getImage())
            };
            i.setImagenes(icons);
            i.setVisible(true);
  
        
    }//GEN-LAST:event_COLIMAActionPerformed

    private void AGUASCALIENTESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGUASCALIENTESActionPerformed
        
         InfoEstado i = new InfoEstado();
            i.setNomEstado("AGUASCALIENTES");
            i.setTitle("AGUASCALIENTES(AGUASCALIENTES)");
            i.setNomcapital("Aguascalientes");
            i.setComida("Gallina en salsa envinada, Cabrito al horno, El puchero");
            ///yucatan.wav
            //i.setMusica("file:/C:/MapaAudio/aguas.wav");
            i.setPersonaje1("Jesus Teran Peredo");
            i.setPersonaje2("José Guadalupe Posada");
            i.setPersonaje3("Jose Ma. Bocanegra");
            i.setPersonaje4("Jose Ma. Chavez");
            i.setRxtension("385 km²");
            i.setMunicipios("11");
            i.setHabitantes("1,425,028 millones de personas");
            // i.setLargo(50, 350, 400, 300);//320
            i.setEscudo("/Imagenes/escudoaguascalientes.png");
            i.setMapa("/Imagenes/mapaaguascalientes.png");

            String[] regiones = {"Montañosa", "",
                "Occidental", "Planicie Oriental", "",
                "", "",
                "", "", "",
                "", "",
                "", "", "", ""};
            i.setRegiones(regiones);

            String[] tradiciones = {"Feria Nacional de San Marcos",
                "La feria del Señor del Encino", "Feria regional del maíz",
                "La feria de la Asunción"
            };
            i.setTradiciones(tradiciones);

            Icon icons[] = {
                new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionesaguas.jpg")).getImage()),
                new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionesaguas3.jpg")).getImage()),
                new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionesaguas4.jpg")).getImage()),
                new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/tradicionesaguas5.jpg")).getImage())
            };
            i.setImagenes(icons);
            i.setVisible(true);
      
        
    }//GEN-LAST:event_AGUASCALIENTESActionPerformed

    private void reproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reproActionPerformed

    private void pausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pausaActionPerformed

    private void CENTROAMERICAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CENTROAMERICAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CENTROAMERICAActionPerformed
 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AGUASCALIENTES;
    private javax.swing.JButton BAJACALIFORNIANORTE;
    private javax.swing.JButton BAJACALIFORNIASUR;
    private javax.swing.JButton CAMPECHE;
    private javax.swing.JButton CENTROAMERICA;
    private javax.swing.JButton CHIAPAS;
    private javax.swing.JButton CHIHUAHUA;
    private javax.swing.JButton COAHUILA;
    private javax.swing.JButton COLIMA;
    private javax.swing.JButton DURANGO;
    private javax.swing.JButton ESTADOS;
    private javax.swing.JButton EUA;
    private javax.swing.JButton GOLFODEMEXICO;
    private javax.swing.JButton GUERRERO;
    private javax.swing.JButton INFO;
    private javax.swing.JButton JALISCO;
    private javax.swing.JButton MICHOACAN;
    private javax.swing.JButton NAYARIT;
    private javax.swing.JButton NUEVOLEON;
    private javax.swing.JButton OAXACA;
    private javax.swing.JButton OCEANOPACIFICO;
    private javax.swing.JButton QUINTANAROO;
    private javax.swing.JButton SANLUIS;
    private javax.swing.JButton SINALOA;
    private javax.swing.JButton SONORA;
    private javax.swing.JButton TABASCO;
    private javax.swing.JButton TAMAULIPAS;
    private javax.swing.JButton VERACRUZ;
    private javax.swing.JButton YUCATAN;
    private javax.swing.JButton ZACATECAS;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton pausa;
    private javax.swing.JButton repro;
    // End of variables declaration//GEN-END:variables
}
